import type { Genre } from '@/lib/ai-engine/types'
import type { GenreTypography } from './types'

// Google Fonts — all loaded via next/font or CDN at runtime
export const GENRE_TYPOGRAPHY: Record<Genre, GenreTypography> = {
  'thriller': {
    titleFont:    'Oswald',
    authorFont:   'Lato',
    titleWeight:  '700',
    titleCase:    'uppercase',
    letterSpacing: 0.08,
    titleColor:   '#FFFFFF',
    authorColor:  '#C0C0C0',
    subtitleColor:'#AAAAAA',
  },
  'romance': {
    titleFont:    'Playfair Display',
    authorFont:   'Cormorant Garamond',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.02,
    titleColor:   '#FFFFFF',
    authorColor:  '#F9E4B7',
    subtitleColor:'#E8C99A',
  },
  'fantasy': {
    titleFont:    'Cinzel Decorative',
    authorFont:   'Raleway',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.05,
    titleColor:   '#F0E6FF',
    authorColor:  '#C9B8FF',
    subtitleColor:'#B0A0DD',
  },
  'sci-fi': {
    titleFont:    'Rajdhani',
    authorFont:   'Exo 2',
    titleWeight:  '700',
    titleCase:    'uppercase',
    letterSpacing: 0.12,
    titleColor:   '#00FFFF',
    authorColor:  '#88DDFF',
    subtitleColor:'#66BBDD',
  },
  'mystery': {
    titleFont:    'EB Garamond',
    authorFont:   'Lato',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.03,
    titleColor:   '#F5F0E8',
    authorColor:  '#D4C9B0',
    subtitleColor:'#B8A99A',
  },
  'horror': {
    titleFont:    'Creepster',
    authorFont:   'Raleway',
    titleWeight:  '700',
    titleCase:    'uppercase',
    letterSpacing: 0.06,
    titleColor:   '#FF2200',
    authorColor:  '#DDDDDD',
    subtitleColor:'#AAAAAA',
  },
  'business': {
    titleFont:    'Montserrat',
    authorFont:   'Open Sans',
    titleWeight:  '800',
    titleCase:    'uppercase',
    letterSpacing: 0.05,
    titleColor:   '#FFFFFF',
    authorColor:  '#E0E0E0',
    subtitleColor:'#BBBBBB',
  },
  'self-help': {
    titleFont:    'Nunito',
    authorFont:   'Open Sans',
    titleWeight:  '800',
    titleCase:    'capitalize',
    letterSpacing: 0.02,
    titleColor:   '#FFFFFF',
    authorColor:  '#FFE066',
    subtitleColor:'#FFCC44',
  },
  'memoir': {
    titleFont:    'Merriweather',
    authorFont:   'Georgia',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.01,
    titleColor:   '#F8F4EC',
    authorColor:  '#D4C5A9',
    subtitleColor:'#B8A88A',
  },
  'christian': {
    titleFont:    'Lora',
    authorFont:   'Open Sans',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.02,
    titleColor:   '#FFFFFF',
    authorColor:  '#F0E8CC',
    subtitleColor:'#D4C8A0',
  },
  'children': {
    titleFont:    'Fredoka One',
    authorFont:   'Nunito',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.03,
    titleColor:   '#FFFFFF',
    authorColor:  '#FFE566',
    subtitleColor:'#FFCC33',
  },
  'literary-fiction': {
    titleFont:    'Libre Baskerville',
    authorFont:   'Libre Baskerville',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.04,
    titleColor:   '#FFFFFF',
    authorColor:  '#E0D5C5',
    subtitleColor:'#C5B8A0',
  },
  'young-adult': {
    titleFont:    'Bebas Neue',
    authorFont:   'Nunito',
    titleWeight:  '700',
    titleCase:    'uppercase',
    letterSpacing: 0.06,
    titleColor:   '#FFFFFF',
    authorColor:  '#FFD700',
    subtitleColor:'#FFA500',
  },
  'historical-fiction': {
    titleFont:    'Cormorant Garamond',
    authorFont:   'EB Garamond',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.03,
    titleColor:   '#F5EDD5',
    authorColor:  '#D4C5A0',
    subtitleColor:'#B8A880',
  },
  'biography': {
    titleFont:    'Playfair Display',
    authorFont:   'Lato',
    titleWeight:  '700',
    titleCase:    'capitalize',
    letterSpacing: 0.03,
    titleColor:   '#FFFFFF',
    authorColor:  '#E0D5C0',
    subtitleColor:'#C5B8A0',
  },
}

export function getGoogleFontsUrl(genre: Genre): string {
  const t = GENRE_TYPOGRAPHY[genre]
  const families = [t.titleFont, t.authorFont]
    .filter((v, i, a) => a.indexOf(v) === i)
    .map(f => `family=${f.replace(/ /g, '+')}:wght@400;700;800`)
    .join('&')
  return `https://fonts.googleapis.com/css2?${families}&display=swap`
}
